# Generated by Django 3.2.6 on 2021-09-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('created', models.DateTimeField(blank=True, default='datetime now')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
