# Generated by Django 4.0.6 on 2022-09-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_feature_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='created',
        ),
        migrations.AddField(
            model_name='feature',
            name='date',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feature',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feature',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
